README.md
`bundle` is run by `bin/setup`, so no need to run it manually.
=> Simplify setup

spec/controllers/dashboards_controller_spec.rb
> DEPRECATION WARNING: The success? predicate is deprecated and will be removed
> in Rails 6.0. Please use successful? as provided by Rack::Response::Helpers.
=> Fix deprecation warning

config/environments/production.rb
Without this we're getting
> Uglifier::Error: Unexpected token: punc ({). To use ES6 syntax, harmony mode
> must be enabled with Uglifier.new(:harmony => true).
when precompiling assets on Heroku.
=> Add ES6 support to Uglifier

Procfile
This is targetting Heroku, but shouldn't cause problems elsewhere.
See https://mentalized.net/journal/2017/04/22/run-rails-migrations-on-heroku-deploy/
for details.
=> Run migrations on deployment

README.md, script/boilerplate/remove_devise
We occasionally run into the rare exception where we don't actually need Devise.
This script allows us to easily remove it from the freshly initiated project.
=> Add script to remove Devise

.circleci/config.yml
PostgreSQL 10 is widely available, and in particular; available on Heroku, which
makes it a good target for future applications.
=> Upgrade PostgreSQL to 10.6

.circleci/config.yml, Gemfile
CI was using 2.6.1 anyways, because of the relaxed "2.6"-specifier.
=> Bump Ruby to 2.6.1

.rubocop.yml
... not entirely sure why these have grown apart, but I reckon the dotfiles ones
is the proper.
=> Match Rubocop config to the one from our dotfiles

.rubocop.yml
This causes way too much busywork trying to align things to the middle of the
line.
Prefer:
expect(enquiry.possible_states).to eq([
Enquiry::AWAITING_REPLY,
Enquiry::BOOKED,
Enquiry::NOT_BOOKED,
Enquiry::REJECTED
])
Over:
expect(enquiry.possible_states).to eq([
Enquiry::AWAITING_REPLY,
Enquiry::BOOKED,
Enquiry::NOT_BOOKED,
Enquiry::REJECTED
])
See also https://github.com/substancelab/dotfiles/pull/7
=> Don't indent array based on their bracket position (#7)

Gemfile, Gemfile.lock
We're building our assets with node-sass these days, so we probably don't need
sass support in Sprockets anymore.
=> Remove Ruby Sass

Gemfile, Gemfile.lock
V4 drops support for Rails 5, so upgrading to web-console 4.x is an implicit
upgrade to Rails 6 as well; a step we (nor rails) aren't quite ready to take
yet.
See https://github.com/rails/web-console/blob/master/CHANGELOG.markdown#400 for details, or https://github.com/substancelab/rails-boilerplate/pull/260 for what happens on upgrade.
=> Lock down web-console to 3.x

Gemfile, Gemfile.lock
Works around failures on Rails 6:
Failure/Error:
get :show,
:params => {:id => person.to_param},
:session => valid_session
ActionView::Template::Error:
wrong number of arguments (given 2, expected 1)
=> Use RSpec version with support for Rails 6

Gemfile, Gemfile.lock, config/environments/development.rb, config/environments/production.rb, package.json, yarn.lock
It seems like we might not be entirely ready to upgrade to Webpack 4 just yet.
With Webpack 4 we'd be seeing errors like
Failure/Error: = javascript_pack_tag "scripts/application"
ActionView::Template::Error:
Webpacker can't find scripts/application in /home/circleci/repo/public/packs-test/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
on CI, and attempts at fixing it seems to tumble us further down the rabbithole:
$ rake assets:precompile …
=> Lock Webpack(er) to versions before v4

.gitignore
Following the recommendations from
https://github.com/bkeepers/dotenv#what-other-env-files-can-i-use.
=> Ignore local .env files

Gemfile, Gemfile.lock
I can't see a reason to keep the version lock any longer; it seems to be a
leftover from when we were on Rails 5 and web-console 4.0+ meant Rails 6.
=> Allow web-console to upgrade freely

.circleci/config.yml, .circleci/config.yml.example
CI builds have started failing with
Error: Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD to a non-empty value for the
superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
connections without a password. This is *not* recommended.
See PostgreSQL documentation about "trust":
https://www.postgresql.org/docs/current/auth-trust.html
Exited with code 1
Presumably something changed on Circle CI, perhaps in the PostgreSQL image or
version.
=> Looks like we need a password going forward

.rubocop.yml
These should have been removed as part of fca834e with the same
reasoning as there.
=> Remove more superfluous directives

.circleci/config.yml, .circleci/config.yml.example, .rubocop.yml, Gemfile, Gemfile.lock, README_APP.md
Note: This upgrade gives a long list of gems related warnings when running specs:
>/home/olepalm/.rvm/gems/ruby-2.7.0/gems/tzinfo-1.2.5/lib/tzinfo/ruby_core_support.rb:142: warning: Using the last argument as keyword parameters is deprecated
/home/olepalm/.rvm/gems/ruby-2.7.0/gems/tzinfo-1.2.5/lib/tzinfo/ruby_core_support.rb:142: warning: Using the last argument as keyword parameters is deprecated
/home/olepalm/.rvm/gems/ruby-2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/olepalm/.rvm/gems/ruby-2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:110: warning: The called method `initialize' is defined here …
=> Upgrade ruby to 2.7.0

config/environments/production.rb, config/puma.rb
Build failure appears to be caused by https://github.com/rubocop-hq/rubocop/issues/8642
=> Code gardening

package.json, yarn.lock
We load it from babel.config.js, so we should probably have it as part of our packages, no?
> A plugin that enables the re-use of Babel's injected helper code to save on codesize.
See https://babeljs.io/docs/en/babel-plugin-transform-runtime for details.
=> Actually install @babel/plugin-transform-runtime

.circleci/config.yml.example
Our caches tend to grow ever larger, taking ever more time to create and
restore, because we keep installing gems and never remove the unused
ones.
=> Remove unused gems from the bundle before caching

.circleci/config.yml
Circle CI says:
> Legacy images with the prefix "circleci/" will be deprecated on
> December 31, 2021. For faster builds, upgrade your projects with
> next-generation convenience images.
- https://circleci.com/docs/2.0/circleci-images/
=> Switch to modern Circle CIs images

.rubocop.yml
ActiveStorage maintains their own tables in the database by generating the occasional migration. All of those generated migrations are affixed with .active_storage.rb and for some reason they don't seem to adhere to our coding guidelines ;)
=> Don't worry about offenses in generated migrations

Gemfile, Gemfile.lock
It was removed from stdlib in Ruby 3.1, and it seems we still need it for the mail gem.
=> Add net-* gems back

.circleci/config.yml, .circleci/config.yml.example
Images starting with circleci/ have been deprecated, see:
https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
=> Switch to next-gen convencience images

Gemfile.lock
Fixes an issue running guard-livereload:
> 09:51:17 - INFO - Guard is now watching at '/Users/jakob/Projects/FlexFabrikken/Worklab/worklab'
> [1] guard(main)> 09:51:21 - INFO - Browser connected.
> 09:51:21 - ERROR - tried to create Proc object without a block
> #<Thread:0x0000000109235438 /Users/jakob/.rvm/gems/ruby-3.1.2/gems/guard-livereload-2.5.2/lib/guard/livereload/reactor.rb:11 run> terminated with exception (report_on_exception is true):
> /Users/jakob/.rvm/gems/ruby-3.1.2/gems/multi_json-1.13.1/lib/multi_json/options_cache.rb:12:in
> `new': tried to create Proc object without a block (ArgumentError)
=> Bump multi_json

package.json
If we need it going forward we'll have to install it, but right now, it looks like Tailwind is the more likely future.
=> Remove Sass

.circleci/config.yml.example, README_APP.md, config/environments/development.rb
We've unfortunately deployed a file to production on a project that couldn't be eager loaded, which broke the entire application, even though nothing in development and CI warned us.
This is a step towards catching problems like the below, which would otherwise only occur on boot in production mode:
Hold on, I am eager loading the application.
rake aborted!
NameError: uninitialized constant Form::InputGroup::Component
class DateComponent < Form::InputGroup::Component
^^^^^^^^^^^
Did you mean?  Complex
~/frontlobby/app/components/tailwind_ui/application_ui/form/input_group/date_component.rb:5:in
`<module:InputGroup>'
This also gives us a fine opportunity to check everything for compatiblity with Zeitwerk.
=> Verify that we can eager load code

Gemfile.lock
Primarily to get rid of
> Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name =>
> spell_checker)' has been deprecated. Please call
> `DidYouMean.correct_error(error_name, spell_checker)' instead.
=> Upgrade bundler to 2.4.4

config/initializers/devise.rb
This way all our mailers inherit from the same parent, which seems like a good practice with fewer surprises.
=> Use ApplicationMailer as parent for Devise::Mailer

Gemfile.lock
This restores our ability to use caches on Circle CI because we no longer update the bundler version during the build which would change the cache keys, resulting in both these happening in the same build:
> No cache is found for key:  v2-dependencies-VfUsQdg7ZsZuJ7MoXZYjq8KDNuCrinCflbBCC33t_K8=-a7uV79TxB+R2O97bXOKkchW+chIDbbCGuYoEQ7kTm2o=
> ...
> Skipping cache generation, cache already exists for key: v2-dependencies-lOI9Cs0dEuq6mIt_QO6uLzJduGlmoSajBZuSsQ4vXD8=-a7uV79TxB+R2O97bXOKkchW+chIDbbCGuYoEQ7kTm2o=
=> Use the newest bundler

.circleci/config.yml, .circleci/config.yml.example
Circle CIs node orb uses .nvmrc to determine the version of Node to install, if one hasn't explicitly been specified using `node-version`.
However, we use .tool-versions to specify the version of Node to use, so we have to manually extract the version from that file and write it to .nvmrc for the orb to use.
See https://circleci.com/developer/orbs/orb/circleci/node for details.
=> Use orbs to install Node

yarn.lock
It seems https://github.com/substancelab/rails-boilerplate/commit/da3c75ebf71e36e3aa21aa04f81af4e6b8a0a263 somehow broke the build. This change brings it back to green.
=> Upgrade Babel

.tool-versions
18.17.0 is the currently recommended LTS version of NodeJS.
Depends on #1273
=> Upgrade NodeJS to 20.9.0

config/routes.rb
Add default routes for health check and PWA files. These are default in Rails 7.2+ and can be removed if not needed.
=> Add default housekeeping routes

.gitignore
It looks like something is still creating pids in the root directory, perhaps procodile? We don't want to track those in git.
=> Ignore pids

Gemfile, Gemfile.lock, README_APP.md, config.ru
All requests for other domains will be redirected to this domain.
=> Use configured domain as a canonical host
